### ISSUE TITLE
Header problem

### ISSUE THREAD

**Issue by wilfaustino** [dmamontov/rararchiver#2]
I have problem with header. The variable $header in RarArchiver.php on line 343 is not inicialized and is corrupting the rar file...
Somebody could help me?

**Comment by dmamontov** [comment]
fix header

**Comment by wilfaustino** [comment]
![image](https://cloud.githubusercontent.com/assets/20818339/17384491/0532a6f0-59b3-11e6-9be5-e201622ccbf8.png)

Still not working... Sorry, but I dont know what to do...

**Comment by dmamontov** [comment]
Please send your code

**Comment by wilfaustino** [comment]
<?php

require_once 'RarArchiver.php';

$r=new RarArchiver('teste.rar', RarArchiver::CREATE);

if ($r->isRar()) {

```
$r->addFile('teste.xlsx', 'teste.xlsx');
$r->addFile('teste.docx', 'teste.docx');
```

} else {
    echo 'Error: not rar!';
}

?>

**Comment by suharelli** [comment]
The reason is if you have mbstring loaded, it will overload strlen and it will treat binary data as unicode strings and return wrong length of file. In that case you should do something like
`mb_strlen($contents, 'latin1');`
in the addFromString method.

**Comment by belliash** [comment]
This does not work for me too.
I can create RAR archive with this, but then getFileList() returns empty array and I cannot read anything from it. unrar tells that header is broken.

**Comment by atmacola** [comment]
Have to add $header = ''; before line 341 in RarArchiver::writeHeader() to fix the problem. I will send a pull request
