### ISSUE TITLE
Not working AddFromString

### ISSUE THREAD

**Issue by maknol** [dmamontov/rararchiver#3]
Hallo,
my code:
`require_once 'C:\Users\Ttt\vendor\autoload.php';

$rar = new RarArchiver('1.rar', RarArchiver::CREATE);

$rar->addFromString('example.txt', 'Example text');`

in this case, did't do anything, not adding file.
But if i write "2.rar", the class creates 2.rar with text file and all it's ok.
my php is version 7

The error:
Notice: Undefined variable: header in C:\Users\Ttt\vendor\dmamontov\rararchiver\RarArchiver.php on line 345

**Comment by wapmorgan** [comment]
It's working, but in the code there's no initialization of `$header` variable before usage. It's not a relevant error, just notice.

**Comment by dmamontov** [comment]
Really. this will be fixed.
