### ISSUE TITLE
no actual compression

### ISSUE THREAD

**Issue by kamilvlcek** [dmamontov/rararchiver#5]
Hi, 
I tried this library, it nicely creates a rar archive with all files, but the **compresion rate is zero** - the size of the rar archive is the same as the total size of uncompressed (csv) files. While the size of the rar archive is e.g. _6 674 951_ bytes, the ZIP archive size of the same files is _377 568_ Bytes. 

Am I doing something wrong?
Thank you!

**Comment by wapmorgan** [comment]
I think the author should clarify this **small** fact in top of README to avoid misunderstanding.

**Comment by dmamontov** [comment]
This class finally decided to sleep and will work in May.
